{% set name = "kstar" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kstar-{{ version }}.tar.gz
  sha256: 330d178936c7fa327b2f31695fab198c018145ea4701cb7ca98dbe81daaf8a24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8
    - numpy >=1.26
    - pandas >=2.1
    - scipy >=1.11
    - seaborn >=0.13
    - fpdf2 >=2.5
    - requests
    - tqdm

test:
  imports:
    - kstar
    - kstar.random_experiments
    - kstar.analysis
    - kstar.dataset_processing
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/NaegleLab/KSTAR
  summary: 'KSTAR: Kinase-Substrate Transfer to Activity Relationships'
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srcrowl
    - knaegle
    - srcrowl
